Repository Enterprise-CMCS/eAPD, pull requests merged in 2018-08, with the labels that each got.

#914 Submission to "Certify and Submit"
  web/src/i18n/locales/en.yaml
Labels: content

#931 Paragraph spacing
  web/src/i18n/locales/en.yaml
Labels: content

#945 Legacy microcopy cleanup
  web/src/i18n/locales/en.yaml
Labels: content

#967 Updates unit test for FFY Budget Table
  web/src/reducers/budget.js
  web/src/reducers/budget.test.js
Labels: bug

#960 Help text reconfig & rewrites [skip deploy]
  .circleci/config.yml
  web/src/components/__snapshots__/Section.test.js.snap
  web/src/i18n/locales/en.yaml
Labels: P1
