Repository Enterprise-CMCS/eAPD, pull requests merged in 2022-12, with the labels that each got.

#4430 Dmirano/4265 subform button accessibility
  web/src/pages/apd/activities/contractor-costs/ContractorResource/ContractorResourceForm.js
  web/src/pages/apd/activities/oms/Milestone/MilestoneForm.js
  web/src/pages/apd/activities/oms/OutcomesAndMetrics/OutcomeAndMetricForm.js
  web/src/pages/apd/activities/oms/OutcomesAndMetrics/__snapshots__/OutcomeAndMetricForm.test.js.snap
  web/src/pages/apd/activities/state-costs/NonPersonnelCost/NonPersonnelCostForm.js
  web/src/pages/apd/activities/state-costs/StatePerson/StatePersonForm.js
  web/src/pages/apd/key-state-personnel/ApdKeyPersonForm.js
  web/src/pages/apd/key-state-personnel/__snapshots__/ApdKeyPersonForm.test.js.snap
Labels: accessibility

#4414 Nz/4183 FFP Bug
  web/src/pages/apd/activities/cost-allocation/CostAllocateFFPQuarterly.js
  web/src/pages/apd/activities/cost-allocation/CostAllocateFFPQuarterly.test.js
Labels: bug

#4435 Adipasquale/4379 add activity button description
  e2e/cypress/integration/02-apd/01-apd-basics.cy.js
  web/src/layout/nav/SecondaryNav.js
  web/src/layout/nav/SecondaryNav.test.js
Labels: feature

#4335 Nz/4209 new apd page
  api/db/apds.js
  common/schemas/apdNew.js
  e2e/cypress/fixtures/launch-darkly-flags.json
  e2e/cypress/helpers/apd/activity-schedule-summary.js
  e2e/cypress/helpers/apd/apd-overview.js
  e2e/cypress/helpers/apd/assurances-and-compliance.js
  e2e/cypress/helpers/apd/executive-summary.js
  e2e/cypress/helpers/apd/proposed-budget.js
  e2e/cypress/helpers/apd/results-of-previous-activities.js
  e2e/cypress/integration/02-apd/01-apd-basics.cy.js
  e2e/cypress/integration/02-apd/02-default-apd.cy.js
  e2e/cypress/integration/02-apd/03-apd-with-data.cy.js
  e2e/cypress/integration/02-apd/04-apd-budget-checks.cy.js
  e2e/cypress/integration/03-admin/04-admin-check.cy.js
  e2e/cypress/integration/04-bug-tests/01-state-staff-bugs.cy.js
  e2e/cypress/integration/05-mmis/01-mmis-basics.cy.js
  e2e/cypress/support/commands.js
  web/src/layout/header/ApdHeader.js
  web/src/layout/header/Header.js
  web/src/layout/header/__snapshots__/ApdHeader.test.js.snap
  web/src/pages/apd/apd-overview/ApdOverview.js
  web/src/pages/apd/apd-overview/ApdOverview.test.js
  web/src/pages/apd/new/ApdNew.js
  web/src/pages/apd/new/ApdNew.test.js
  web/src/pages/dashboard/state-dashboard/ApdList.js
  web/src/pages/dashboard/state-dashboard/ApdList.test.js
  web/src/pages/mainRoutesList.js
  web/src/redux/actions/app/apd.js
  web/src/redux/actions/app/apd.test.js
  web/src/styles/index.scss
  web/src/styles/scss/forms.scss
  web/src/styles/scss/link-button.scss
Labels: feature

#4412 Tbolt/4411 Fixes issue where PUTs against /states/:stateId/affiliations/:id could assign invalid roles
  api/auth/mockedOktaAuth.js
  api/db/affiliations.js
  api/db/affiliations.livedb.test.js
  api/routes/auth/certifications/__snapshots__/get.endpoint.js.snap
  api/routes/auth/certifications/put.endpoint.js
  api/routes/auth/certifications/put.js
  api/routes/states/affilitations/patch.endpoint.js
  api/routes/states/affilitations/patch.js
  api/routes/states/affilitations/patch.test.js
  api/seeds/test/certifications.js
Labels: bug

#4436 Dmirano/4320 mmis test scaffolding
  .circleci/config.yml
  .gitignore
  e2e/cypress/helpers/apd/activity-schedule-summary.js
  e2e/cypress/helpers/apd/apd-overview.js
  e2e/cypress/helpers/apd/assurances-and-compliance.js
  e2e/cypress/helpers/apd/executive-summary.js
  e2e/cypress/helpers/apd/proposed-budget.js
  e2e/cypress/helpers/apd/results-of-previous-activities.js
  e2e/cypress/integration/02-apd/01-apd-basics.cy.js
  e2e/cypress/integration/02-apd/02-default-apd.cy.js
  e2e/cypress/integration/02-apd/03-apd-with-data.cy.js
  e2e/cypress/integration/02-apd/04-apd-budget-checks.cy.js
  e2e/cypress/integration/04-bug-tests/01-state-staff-bugs.cy.js
  e2e/cypress/integration/05-mmis/01-mmis-basics.cy.js
  e2e/cypress/support/commands.js
Labels: tests
