Repository Enterprise-CMCS/eAPD, pull requests merged in 2022-04, with the labels that each got.

#3911 bbrooks/Update platinum_ami_build.yml
  .github/workflows/platinum_ami_build.yml
Labels: Small, DevOps

#3903 bbrooks/3798-Harden-S3-Backend
  terraform/greenfield/bootstrap/main.tf
  terraform/greenfield/bootstrap/terraform.tfstate
  terraform/greenfield/bootstrap/terraform.tfstate.backup
  terraform/greenfield/bootstrap/variables.tf
Labels: Medium, DevOps

#3960 Dmirano/3788 activity overview restructure
  web/src/containers/activity/OutcomesAndMetrics/OutcomeAndMetricForm.js
  web/src/pages/apd/ApdPageRoutes.js
  web/src/pages/apd/activities/ActivityRoutes.js
  web/src/pages/apd/activities/oms/Milestone/MilestoneForm.js
  web/src/pages/apd/activities/oms/Milestone/MilestoneForm.test.js
  web/src/pages/apd/activities/oms/Milestone/MilestoneReview.js
  web/src/pages/apd/activities/oms/Milestone/MilestoneReview.test.js
  web/src/pages/apd/activities/oms/Milestone/__snapshots__/MilestoneForm.test.js.snap
  web/src/pages/apd/activities/oms/Milestone/__snapshots__/MilestoneReview.test.js.snap
  web/src/pages/apd/activities/oms/Milestone/index.js
  web/src/pages/apd/activities/oms/Milestones.js
  web/src/pages/apd/activities/oms/Milestones.test.js
  web/src/pages/apd/activities/oms/Outcomes.js
  web/src/pages/apd/activities/oms/Outcomes.test.js
  web/src/pages/apd/activities/oms/OutcomesAndMetrics/OutcomeAndMetricForm.js
  web/src/pages/apd/activities/oms/OutcomesAndMetrics/OutcomeAndMetricForm.test.js
  web/src/pages/apd/activities/oms/OutcomesAndMetrics/OutcomeAndMetricReview.js
  web/src/pages/apd/activities/oms/OutcomesAndMetrics/OutcomeAndMetricReview.test.js
  web/src/pages/apd/activities/oms/OutcomesAndMetrics/__snapshots__/OutcomeAndMetricForm.test.js.snap
  web/src/pages/apd/activities/oms/OutcomesAndMetrics/__snapshots__/OutcomeAndMetricReview.test.js.snap
  web/src/pages/apd/activities/oms/OutcomesAndMetrics/index.js
  web/src/pages/apd/activities/oms/__snapshots__/Milestones.test.js.snap
  web/src/pages/apd/activities/oms/__snapshots__/Outcomes.test.js.snap
  web/src/pages/apd/activities/overview/ActivityOverview.js
  web/src/pages/apd/activities/overview/ActivityOverview.test.js
  web/src/pages/apd/activities/overview/NameAndFundingSource/NameAndFundingSourceForm.js
  web/src/pages/apd/activities/overview/NameAndFundingSource/NameAndFundingSourceForm.test.js
  web/src/pages/apd/activities/overview/NameAndFundingSource/NameAndFundingSourceReview.js
  web/src/pages/apd/activities/overview/NameAndFundingSource/NameAndFundingSourceReview.test.js
  web/src/pages/apd/activities/overview/NameAndFundingSource/__snapshots__/NameAndFundingSourceForm.test.js.snap
  web/src/pages/apd/activities/overview/NameAndFundingSource/__snapshots__/NameAndFundingSourceReview.test.js.snap
  web/src/pages/apd/activities/overview/NameAndFundingSource/index.js
  web/src/pages/apd/activities/overview/Overview.js
  web/src/pages/apd/activities/overview/Overview.test.js
  web/src/pages/apd/activities/overview/Schedule.js
  web/src/pages/apd/activities/overview/Schedule.test.js
  web/src/pages/apd/activities/overview/StandardsAndConditions.js
  web/src/pages/apd/activities/overview/StandardsAndConditions.test.js
  web/src/pages/apd/activities/overview/__snapshots__/ActivityOverview.test.js.snap
  web/src/pages/apd/activities/overview/__snapshots__/Overview.test.js.snap
  web/src/pages/apd/activities/overview/__snapshots__/Schedule.test.js.snap
  web/src/pages/apd/activities/overview/__snapshots__/StandardsAndConditions.test.js.snap
Labels: refactor

#3961 Dmirano/3791 staff expenses restructure
  web/src/containers/activity/NonPersonnelCost/NonPersonnelCostForm.js
  web/src/containers/activity/StatePerson/StatePersonForm.js
  web/src/pages/apd/activities/ActivityRoutes.js
  web/src/pages/apd/activities/state-costs/Costs.js
  web/src/pages/apd/activities/state-costs/Costs.test.js
  web/src/pages/apd/activities/state-costs/NonPersonnelCost/NonPersonnelCostForm.js
  web/src/pages/apd/activities/state-costs/NonPersonnelCost/NonPersonnelCostForm.test.js
  web/src/pages/apd/activities/state-costs/NonPersonnelCost/NonPersonnelCostReview.js
  web/src/pages/apd/activities/state-costs/NonPersonnelCost/NonPersonnelCostReview.test.js
  web/src/pages/apd/activities/state-costs/NonPersonnelCost/__snapshots__/NonPersonnelCostForm.test.js.snap
  web/src/pages/apd/activities/state-costs/NonPersonnelCost/__snapshots__/NonPersonnelCostReview.test.js.snap
  web/src/pages/apd/activities/state-costs/NonPersonnelCost/index.js
  web/src/pages/apd/activities/state-costs/NonPersonnelCosts.js
  web/src/pages/apd/activities/state-costs/NonPersonnelCosts.test.js
  web/src/pages/apd/activities/state-costs/StatePerson/StatePersonForm.js
  web/src/pages/apd/activities/state-costs/StatePerson/StatePersonForm.test.js
  web/src/pages/apd/activities/state-costs/StatePerson/StatePersonReview.js
  web/src/pages/apd/activities/state-costs/StatePerson/StatePersonReview.test.js
  web/src/pages/apd/activities/state-costs/StatePerson/__snapshots__/StatePersonForm.test.js.snap
  web/src/pages/apd/activities/state-costs/StatePerson/__snapshots__/StatePersonReview.test.js.snap
  web/src/pages/apd/activities/state-costs/StatePerson/index.js
  web/src/pages/apd/activities/state-costs/StatePersonnel.js
  web/src/pages/apd/activities/state-costs/StatePersonnel.test.js
  web/src/pages/apd/activities/state-costs/__snapshots__/Costs.test.js.snap
  web/src/pages/apd/activities/state-costs/__snapshots__/NonPersonnelCosts.test.js.snap
  web/src/pages/apd/activities/state-costs/__snapshots__/StatePersonnel.test.js.snap
Labels: refactor

#3962 Dmirano/3792 contractor restructure
  web/src/pages/apd/activities/ActivityRoutes.js
  web/src/pages/apd/activities/contractor-costs/ContractorResource/ContractorResourceForm.js
  web/src/pages/apd/activities/contractor-costs/ContractorResource/ContractorResourceForm.test.js
  web/src/pages/apd/activities/contractor-costs/ContractorResource/ContractorResourceReview.js
  web/src/pages/apd/activities/contractor-costs/ContractorResource/ContractorResourceReview.test.js
  web/src/pages/apd/activities/contractor-costs/ContractorResource/__snapshots__/ContractorResourceForm.test.js.snap
  web/src/pages/apd/activities/contractor-costs/ContractorResource/__snapshots__/ContractorResourceReview.test.js.snap
  web/src/pages/apd/activities/contractor-costs/ContractorResource/index.js
  web/src/pages/apd/activities/contractor-costs/ContractorResources.js
  web/src/pages/apd/activities/contractor-costs/ContractorResources.test.js
  web/src/pages/apd/activities/contractor-costs/__snapshots__/ContractorResources.test.js.snap
Labels: refactor

#3976 Dmirano/3793 cost allocation restructure
  web/src/containers/activity/CostAllocateFFP.js
  web/src/pages/apd/activities/ActivityRoutes.js
  web/src/pages/apd/activities/cost-allocation/CostAllocateFFPQuarterly.js
  web/src/pages/apd/activities/cost-allocation/CostAllocateFFPQuarterly.test.js
  web/src/pages/apd/activities/cost-allocation/CostAllocation/CostAllocate.js
  web/src/pages/apd/activities/cost-allocation/CostAllocation/CostAllocate.test.js
  web/src/pages/apd/activities/cost-allocation/CostAllocation/OtherFunding.js
  web/src/pages/apd/activities/cost-allocation/CostAllocation/OtherFunding.test.js
  web/src/pages/apd/activities/cost-allocation/CostAllocation/__snapshots__/CostAllocate.test.js.snap
  web/src/pages/apd/activities/cost-allocation/CostAllocation/__snapshots__/OtherFunding.test.js.snap
  web/src/pages/apd/activities/cost-allocation/CostAllocation/index.js
  web/src/pages/apd/activities/cost-allocation/CostAllocationRows.js
  web/src/pages/apd/activities/cost-allocation/CostAllocationRows.test.js
  web/src/pages/apd/activities/cost-allocation/__snapshots__/CostAllocateFFPQuarterly.test.js.snap
  web/src/pages/apd/activities/cost-allocation/__snapshots__/CostAllocationRows.test.js.snap
  web/src/pages/apd/proposed-budget/SummaryActivityBreakdown.js
Labels: refactor

#3977 Dmirano/3794 ffp components restructure
  web/src/app.dev.js
  web/src/app.js
  web/src/components/App.js
  web/src/components/AriaAnnounce.js
  web/src/components/AriaAnnounce.test.js
  web/src/components/ConnectedWaypoint.js
  web/src/components/ConnectedWaypoint.test.js
  web/src/components/PrivateRoute.js
  web/src/components/PrivateRoute.test.js
  web/src/components/SessionEndingAlert.js
  web/src/components/SessionEndingAlert.test.js
  web/src/components/UnexpectedError.js
  web/src/components/UnexpectedError.test.js
  web/src/components/Wrapper.js
  web/src/components/__snapshots__/AriaAnnounce.test.js.snap
  web/src/components/__snapshots__/PrivateRoute.test.js.snap
  web/src/components/__snapshots__/UnexpectedError.test.js.snap
  web/src/containers/ApdApplication.js
  web/src/containers/App.js
  web/src/containers/App.test.js
  web/src/containers/Root.js
  web/src/containers/Root.test.js
  web/src/containers/__snapshots__/App.test.js.snap
  web/src/containers/__snapshots__/Root.test.js.snap
  web/src/pages/Route.js
  web/src/pages/apd/ApdReadOnly.js
  web/src/pages/apd/activities/ActivityRoutes.js
  web/src/pages/apd/activities/activities-dashboard/ActivitiesDashboard.js
  web/src/pages/apd/activities/activities-dashboard/ActivityReadOnly.js
  web/src/pages/apd/activities/ffp/CostAllocateFFP.js
  web/src/pages/apd/activities/ffp/CostAllocateFFP.test.js
  web/src/pages/apd/activities/ffp/__snapshots__/CostAllocateFFP.test.js.snap
  web/src/pages/apd/executive-summary/ExecutiveSummary.js
  web/src/pages/apd/export/ApdExport.js
  web/src/pages/apd/export/ReadOnlyApd.js
  web/src/pages/apd/export/ReadOnlyApd.test.js
  web/src/pages/apd/key-state-personnel/KeyStatePersonnel.js
  web/src/pages/apd/previous-activities/PreviousActivities.js
  web/src/pages/apd/proposed-budget/ProposedBudget.js
  web/src/pages/apd/schedule-summary/ScheduleSummary.js
  web/src/pages/dashboard/Dashboard.js
  web/src/pages/dashboard/Dashboard.test.js
  web/src/pages/dashboard/__snapshots__/Dashboard.test.js.snap
  web/src/pages/routes.js
Labels: refactor

#3998 bbrooks/Update-Mongo-SG-Terraform
  packer/mongo-ami.pkr.hcl
  terraform/legacy/prod/modules/securityGroups.tf
  terraform/legacy/prod/prod.tf
  terraform/legacy/staging/modules/securityGroups.tf
Labels: Small, DevOps
