Repository Enterprise-CMCS/eAPD, pull requests merged in 2022-08, with the labels that each got.

#4248 Assurances and Compliance error messages
  .github/PULL_REQUEST_TEMPLATE.md
  common/schemas/assurancesAndCompliance.js
  e2e/cypress/helpers/apd/assurances-and-compliance.js
  e2e/cypress/helpers/apd/key-state-personnel.js
  web/src/pages/apd/ApdReadOnly.test.js
  web/src/pages/apd/activities/contractor-costs/ContractorResource/ContractorResourceForm.test.js
  web/src/pages/apd/activities/overview/NameAndFundingSource/NameAndFundingSourceForm.js
  web/src/pages/apd/activities/overview/Overview.js
  web/src/pages/apd/activities/overview/Schedule.js
  web/src/pages/apd/activities/overview/StandardsAndConditions.js
  web/src/pages/apd/assurances-and-compliance/AssurancesAndCompliance.js
  web/src/pages/apd/assurances-and-compliance/AssurancesAndCompliance.test.js
  web/src/pages/apd/assurances-and-compliance/__snapshots__/AssurancesAndCompliance.test.js.snap
  web/src/pages/apd/key-state-personnel/ApdStateProfileMedicaidOffice.js
  web/src/redux/reducers/apd.js
  web/src/redux/reducers/apd.test.js
Labels: feature

#4255 Tbolt/3495 Update activities error message to only show when admin check enabled
  common/schemas/activitiesDashboard.js
  e2e/cypress/integration/02-apd/01-apd-basics.cy.js
  web/src/pages/apd/activities/activities-dashboard/ActivitiesDashboard.js
  web/src/pages/apd/activities/activities-dashboard/ActivitiesDashboard.test.js
Labels: feature

#4277 Tbolt/2675 rich text editor lables
  web/src/components/RichText.js
  web/src/components/RichText.test.js
  web/src/components/__snapshots__/RichText.test.js.snap
  web/src/pages/apd/activities/contractor-costs/ContractorResource/ContractorResourceForm.js
  web/src/pages/apd/activities/cost-allocation/CostAllocation/CostAllocate.js
  web/src/pages/apd/activities/cost-allocation/CostAllocation/OtherFunding.js
  web/src/pages/apd/activities/cost-allocation/CostAllocation/__snapshots__/CostAllocate.test.js.snap
  web/src/pages/apd/activities/cost-allocation/CostAllocation/__snapshots__/OtherFunding.test.js.snap
  web/src/pages/apd/activities/overview/Overview.js
  web/src/pages/apd/activities/overview/StandardsAndConditions.js
  web/src/pages/apd/apd-overview/ApdOverview.js
  web/src/pages/apd/previous-activities/PreviousActivities.js
  web/src/pages/apd/previous-activities/__snapshots__/PreviousActivities.test.js.snap
Labels: accessibility, feature

#4284 Dmirano/4238 cypress budget checks
  .circleci/config.yml
  e2e/cypress/fixtures/budget-checks-test.json
  e2e/cypress/helpers/apd/budget-checks.js
  e2e/cypress/integration/02-apd/04-apd-budget-checks.cy.js
  e2e/cypress/page-objects/fill-out-activity-page.js
  e2e/cypress/page-objects/proposed-budget-page.js
Labels: tests
