Repository Enterprise-CMCS/eAPD, pull requests merged in 2022-05, with the labels that each got.

#3980 Tbolt/3726 Subform Enhancement
  integrationTests/cypress/integration/02-apd/01-apd-basics.spec.js
  web/src/components/FormAndReviewList.js
  web/src/components/__snapshots__/FormAndReviewList.test.js.snap
  web/src/styles/scss/forms.scss
Labels: feature

#4034 bbrooks/4027-Remove_Dedicated_Tenancy
  bin/prod-deploy/aws.sh
Labels: DevOps, Extra Small

#3969 Tbolt/3346 APD Overview Validation
  api/package.json
  integrationTests/cypress/integration/02-apd/01-apd-basics.spec.js
  web/src/pages/apd/apd-overview/ApdOverview.js
  web/src/pages/apd/apd-overview/ApdOverview.test.js
  web/src/static/schemas/apdOverview.js
Labels: feature

#4000 Tbolt/3449 Updates to default messages for empty fields in export view
  api/package.json
  api/routes/apds/__snapshots__/post.endpoint.js.snap
  api/routes/apds/post.data.js
  api/routes/apds/post.data.test.js
  api/routes/apds/post.test.js
  integrationTests/cypress-setup.sh
  integrationTests/cypress/fixtures/default-activity-template.json
  integrationTests/cypress/helpers/apd/activity-schedule-summary.js
  integrationTests/cypress/helpers/apd/assurances-and-compliance.js
  integrationTests/cypress/page-objects/budget-page.js
  web/src/pages/apd/activities/activities-dashboard/ActivityReadOnly.js
  web/src/pages/apd/assurances-and-compliance/AssurancesAndComplianceReadOnly.js
  web/src/pages/apd/schedule-summary/ScheduleSummaryReadOnly.js
Labels: feature

#3957 Tbolt/3498 Other state expenses validation
  integrationTests/cypress/helpers/apd/activity/add-HIE-activity.js
  integrationTests/cypress/helpers/apd/activity/add-HIT-activity.js
  integrationTests/cypress/helpers/apd/activity/add-MMIS-activity.js
  integrationTests/cypress/integration/02-apd/01-apd-basics.spec.js
  integrationTests/cypress/page-objects/activities-state-staff-expenses-page.js
  integrationTests/cypress/page-objects/fill-out-activity-page.js
  web/src/i18n/locales/en/activities/expenses.yaml
  web/src/pages/apd/activities/state-costs/NonPersonnelCost/NonPersonnelCostForm.js
  web/src/pages/apd/activities/state-costs/NonPersonnelCost/NonPersonnelCostForm.test.js
  web/src/pages/apd/activities/state-costs/NonPersonnelCost/__snapshots__/NonPersonnelCostForm.test.js.snap
  web/src/pages/apd/activities/state-costs/StatePerson/StatePersonForm.js
  web/src/pages/apd/activities/state-costs/__snapshots__/NonPersonnelCosts.test.js.snap
  web/src/static/schemas/nonPersonnelCosts.js
Labels: feature

#4070 Adding missing var and updating trigger for testing
  .circleci/config.yml
Labels: Small, DevOps

#4067 Resolves security vulnerabilities, test errors, enables chromatic build
  .circleci/config.yml
  api/api.js
  api/auth/jwtUtils.js
  api/middleware/auth.js
  api/package.json
  api/routes/apds/files/post.js
  api/routes/apds/files/post.test.js
  api/routes/auth/certifications/files/post.js
  api/routes/auth/certifications/files/post.test.js
  api/util/fileValidation.js
  api/yarn.lock
  docker-compose.yml
  integrationTests/yarn.lock
  web/audit-ci.json
  web/package.json
  web/src/components/CardForm.test.js
  web/src/components/UpgradeBrowser.js
  web/src/components/UpgradeBrowser.story.js
  web/src/containers/ApdApplication.test.js
  web/src/layout/header/HeaderSaveMessage.story.js
  web/src/pages/apd/ApdPageRoutes.js
  web/src/pages/apd/ApdPageRoutes.test.js
  web/src/pages/apd/ApdReadOnly.test.js
  web/src/pages/apd/activities/activities-dashboard/ActivitiesDashboard.test.js
  web/src/pages/apd/activities/contractor-costs/ContractorResource/ContractorResourceForm.test.js
  web/src/pages/apd/activities/overview/ActivityOverview.test.js
  web/src/pages/apd/executive-summary/ExecutiveSummary.test.js
  web/src/pages/apd/export/ApdExport.js
  web/src/pages/apd/export/ApdExport.test.js
  web/src/pages/dashboard/state-dashboard/AffiliationStatus.test.js
  web/src/pages/login/LoginForm.test.js
  web/src/redux/actions/admin.js
  web/src/redux/actions/auth.js
  web/src/redux/actions/editApd/uploadFile.js
  web/src/redux/actions/editApd/uploadFile.test.js
  web/src/redux/selectors/user.selector.js
  web/src/util/auth.js
  web/webpack.config.dev.js
  web/webpack.config.js
  web/yarn.lock
Labels: refactor
