Repository Enterprise-CMCS/eAPD, pull requests merged in 2022-06, with the labels that each got.

#4080 Dmirano/3979 errors warning cleanup
  e2e/cypress/support/commands.js
  e2e/package.json
  package-lock.json
  web/src/components/PercentField.js
  web/src/components/PrivateRoute.js
  web/src/components/SessionEndingAlert.js
  web/src/components/__snapshots__/PercentField.test.js.snap
  web/src/layout/header/DashboardButton.js
  web/src/layout/header/Header.js
  web/src/pages/admin/AdminRoute.js
  web/src/pages/apd/ApdReadOnly.js
  web/src/pages/apd/activities/oms/OutcomesAndMetrics/OutcomeAndMetricReview.js
  web/src/pages/apd/activities/oms/OutcomesAndMetrics/__snapshots__/OutcomeAndMetricReview.test.js.snap
  web/src/pages/apd/key-state-personnel/ApdKeyPersonForm.js
  web/src/pages/apd/key-state-personnel/ApdKeyPersonReview.js
  yarn.lock
Labels: bug

#4005 Nz/3349 activity overview inline
  .circleci/config.yml
  api/Dockerfile
  api/seeds/development/apds.js
  common/schemas/activityOverview.js
  common/schemas/nameAndFundingSource.js
  common/schemas/plannedActivityShedule.js
  common/schemas/standardsAndConditions.js
  e2e/cypress/fixtures/activity-overview-template.json
  e2e/package.json
  postman/hitech-apd.postman_collection.json
  web/Dockerfile
  web/src/components/DateField.js
  web/src/fixtures/mo-hitech-apd.js
  web/src/pages/apd/ApdPageRoutes.test.js
  web/src/pages/apd/activities/overview/NameAndFundingSource/NameAndFundingSourceForm.js
  web/src/pages/apd/activities/overview/NameAndFundingSource/NameAndFundingSourceForm.test.js
  web/src/pages/apd/activities/overview/NameAndFundingSource/__snapshots__/NameAndFundingSourceForm.test.js.snap
  web/src/pages/apd/activities/overview/Overview.js
  web/src/pages/apd/activities/overview/Overview.test.js
  web/src/pages/apd/activities/overview/Schedule.js
  web/src/pages/apd/activities/overview/Schedule.test.js
  web/src/pages/apd/activities/overview/StandardsAndConditions.js
  web/src/pages/apd/activities/overview/StandardsAndConditions.test.js
  web/src/pages/apd/activities/overview/__snapshots__/Overview.test.js.snap
  web/src/pages/apd/activities/overview/__snapshots__/Schedule.test.js.snap
  web/src/pages/apd/activities/overview/__snapshots__/StandardsAndConditions.test.js.snap
  web/src/redux/actions/app/apd.js
  web/src/redux/actions/app/symbols.js
  web/src/redux/reducers/apd.js
  web/src/redux/reducers/apd.test.js
  web/src/static/schemas/privateContractor.js
  yarn.lock
Labels: feature

#4153 fixed file that was overwritten with older version
  .github/PULL_REQUEST_TEMPLATE.md
  api/db/users.js
  api/db/users.test.js
  api/seeds/shared/set-up-users.js
Labels: bug

#4151 Dmirano/4077 cypress image upload
  .gitignore
  e2e/cypress/fixtures/cms-logo.png
  e2e/cypress/integration/02-apd/01-apd-basics.cy.js
  e2e/cypress/support/commands.js
  e2e/package.json
  yarn.lock
Labels: tests
