Repository Enterprise-CMCS/eAPD, pull requests merged in 2022-07, with the labels that each got.

#4163 Tbolt/4047 Stop subform submission when hitting enter
  web/src/pages/apd/activities/contractor-costs/ContractorResource/ContractorResourceForm.js
  web/src/pages/apd/activities/oms/Milestone/MilestoneForm.js
  web/src/pages/apd/activities/oms/OutcomesAndMetrics/OutcomeAndMetricForm.js
  web/src/pages/apd/activities/oms/OutcomesAndMetrics/__snapshots__/OutcomeAndMetricForm.test.js.snap
  web/src/pages/apd/activities/state-costs/NonPersonnelCost/NonPersonnelCostForm.js
  web/src/pages/apd/activities/state-costs/StatePerson/StatePersonForm.js
  web/src/pages/apd/key-state-personnel/ApdKeyPersonForm.js
  web/src/pages/apd/key-state-personnel/__snapshots__/ApdKeyPersonForm.test.js.snap
Labels: bug

#4158 Tbolt/3445 hit hie mmis validation updates
  babel.config.js
  common/schemas/apdOverview.js
  web/src/pages/apd/apd-overview/ApdOverview.js
  web/src/redux/selectors/activities.selectors.js
Labels: feature

#4171 dmirano/update-bug-template
  .github/ISSUE_TEMPLATE/bug.md
Labels: documentation

#4174 dmirano/4147-cypress-component-testing
  web/src/pages/apd/activities/contractor-costs/ContractorResources.cy.js
Labels: development, tests

#4175 Tbolt/4164 Fixes issue where unable to add duplicate state admin certifications
  api/migrations/20220701132738_update-state-admin-cert-unique-constraint.js
  api/package.json
  audit-ci.json
  e2e/cypress/integration/03-admin/01-delegate-state-admin-form.cy.js
  web/package.json
  yarn.lock
Labels: bug

#4220 tealium updates
  .circleci/config.yml
  .gitignore
  bin/preview-deploy/aws.sh
  docker-compose.yml
  web/src/redux/reducers/apd.js
  web/src/util/analytics.js
  web/webpack.config.dev.js
  web/webpack.config.js
Labels: bug

#4225 update tealium configs
  .circleci/config.yml
  bin/preview-deploy/aws.sh
  bin/preview-deploy/aws.user-data.sh
  bin/prod-deploy/aws.sh
  docker-compose.yml
  web/src/redux/reducers/apd.js
  web/src/util/analytics.js
  web/webpack.config.dev.js
  web/webpack.config.js
Labels: bug

#4227 update node to 16.16.0
  .circleci/config.yml
  .github/workflows/storybook.yml
  .nvmrc
  README.md
  StatementOfObjectives.md
  api/Dockerfile
  api/package.json
  api/seeds/shared/set-up-users.js
  bin/preview-deploy/aws.user-data.sh
  bin/prod-deploy/aws.user-data.sh
  common/package.json
  e2e/cypress/page-objects/fill-out-activity-page.js
  e2e/package.json
  package.json
  packer/backend20220608.sh
  packer/mongo20220708.sh
  packer/preview20220608.sh
  web/Dockerfile
  web/package.json
  web/src/components/__snapshots__/DollarField.test.js.snap
  web/src/components/__snapshots__/PercentField.test.js.snap
  web/src/components/__snapshots__/UnexpectedError.test.js.snap
  web/src/layout/header/__snapshots__/ApdHeader.test.js.snap
  web/src/layout/header/__snapshots__/Header.test.js.snap
  web/src/layout/nav/__snapshots__/Nav.test.js.snap
  web/src/pages/apd/activities/oms/OutcomesAndMetrics/__snapshots__/OutcomeAndMetricForm.test.js.snap
  web/src/pages/apd/key-state-personnel/__snapshots__/ApdKeyPersonForm.test.js.snap
  yarn-error.log
  yarn.lock
Labels: dependencies

#4178 tforkner/3556-move-budget moved budget to common
  .prettierrc
  api/seeds/test/04-APD.json
  api/seeds/test/05-APD.json
  api/seeds/test/06-APD.json
  api/seeds/test/07-APD.json
  audit-ci.json
  common/.eslintignore
  common/.eslintrc.json
  common/babel.config.js
  common/jest.config.js
  common/package.json
  common/stryker.conf.json
  common/utils/budget-default.test.js
  common/utils/budget-sums.test.js
  common/utils/budget-utils.test.js
  common/utils/budget.js
  common/utils/budget.test.js
  common/utils/formatting.js
  common/utils/formatting.test.js
  common/utils/roundedPercents.js
  common/utils/roundedPercents.test.js
  common/utils/utils.js
  documentation/api-diagram.md
  documentation/architecture-diagram.mmd
  documentation/architecture-diagram.png
  documentation/database-diagram.md
  documentation/database-diagram.png
  documentation/mongo_database-diagram.mmd
  documentation/mongo_database-diagram.png
  documentation/postgres_database-diagram.mmd
  documentation/postgres_database-diagram.png
  documentation/sequence-diagram-authentication.mmd
  documentation/sequence-diagram-authorization.mmd
  web/package.json
  web/src/redux/reducers/activities.js
  web/src/redux/reducers/budget.js
  web/src/redux/reducers/budget.test.js
  web/src/util/index.js
  web/src/util/index.test.js
  yarn.lock
Labels: feature

#4235 Dmirano/4169 cypress bug tests
  .circleci/config.yml
  e2e/cypress/integration/04-bug-tests/01-state-staff-bugs.cy.js
Labels: tests

#4244 removed google tag manager
  bin/headers-production.lambda.js
  bin/headers-staging.lambda.js
  web/package.json
  web/src/containers/ApdApplication.js
  web/src/containers/Root.js
  web/src/pages/dashboard/state-dashboard/StateDashboard.js
  yarn.lock
Labels: bug
