Repository Enterprise-CMCS/eAPD, pull requests merged in 2023-01, with the labels that each got.

#4462 Dmirano/4431 security planning page
  e2e/cypress/integration/05-mmis/01-mmis-basics.cy.js
  e2e/cypress/support/commands.js
  web/src/i18n/locales/en/securityPlanning.yaml
  web/src/pages/apd/security-planning/SecurityPlanning.js
  web/src/redux/actions/editApd/index.js
  web/src/redux/actions/editApd/securityPlanning.js
  web/src/redux/selectors/apd.selectors.js
Labels: feature, tests

#4445 [Feature] #4415 Activities Overview for MMIS
  api/seeds/development/03-mmis.js
  api/util/adminCheck.test.js
  common/schemas/activityOverview.js
  common/schemas/nameAndFundingSource.js
  e2e/cypress/integration/05-mmis/01-mmis-basics.cy.js
  e2e/cypress/support/commands.js
  web/src/i18n/locales/en/activities/comprehensiveOverview.yaml
  web/src/i18n/locales/en/activities/index.js
  web/src/i18n/locales/en/activities/overview.yaml
  web/src/pages/apd/activities/__snapshots__/ActivityRoutes.test.js.snap
  web/src/pages/apd/activities/activityRoutesList.js
  web/src/pages/apd/activities/overview/FundingSourceForm.js
  web/src/pages/apd/activities/overview/HITECHOverview.js
  web/src/pages/apd/activities/overview/HITECHOverview.test.js
  web/src/pages/apd/activities/overview/MMISOverview.js
  web/src/pages/apd/activities/overview/MMISOverview.test.js
  web/src/pages/apd/activities/overview/NameAndFundingSource/NameAndFundingSourceForm.js
  web/src/pages/apd/activities/overview/NameAndFundingSource/NameAndFundingSourceReview.js
  web/src/pages/apd/activities/overview/NameAndFundingSource/NameAndFundingSourceReview.test.js
  web/src/pages/apd/activities/overview/NameAndFundingSource/__snapshots__/NameAndFundingSourceReview.test.js.snap
  web/src/pages/apd/activities/overview/NameAndFundingSource/index.js
  web/src/pages/apd/activities/overview/NameForm.js
  web/src/pages/apd/activities/overview/NameForm.test.js
  web/src/pages/apd/activities/overview/Overview.js
  web/src/redux/actions/editActivity/overview.js
  web/src/redux/actions/editActivity/overview.test.js
Labels: feature

#4456 NZ/4441 feature temporary message
  audit-ci.json
  e2e/cypress/helpers/apd/apd-overview.js
  e2e/cypress/integration/02-apd/01-apd-basics.cy.js
  web/src/components/TempAlert.js
  web/src/components/TempAlert.test.js
  web/src/pages/apd/apd-overview/ApdOverview.js
  web/src/pages/apd/new/ApdNew.js
  web/src/redux/actions/alert.js
  web/src/redux/actions/app/apd.js
  web/src/redux/actions/app/apd.test.js
  web/src/redux/actions/aria.js
  web/src/redux/reducers/alerts.js
  web/src/redux/reducers/alerts.test.js
  web/src/redux/reducers/errors.js
  web/src/redux/reducers/errors.test.js
  web/src/redux/reducers/index.js
  web/src/redux/reducers/index.test.js
  web/src/redux/selectors/alerts.selectors.js
  web/src/styles/scss/card.scss
Labels: feature

#4454 Tbolt/4413 key state personnel mmis
  api/models/apd.js
  api/mongo-migrations/1671458857144-key-state-personnel-mmis.js
  api/routes/apds/__snapshots__/patch.endpoint.js.snap
  api/schemas/apd.json
  api/seeds/development/01-hitech.js
  api/seeds/development/02-hitechNoActivities.js
  api/seeds/development/03-mmis.js
  api/seeds/test/01-mnAPD.json
  api/seeds/test/02-akAPD.json
  common/schemas/keyStatePersonnel.js
  e2e/cypress/fixtures/users.json
  e2e/cypress/integration/05-mmis/01-mmis-basics.cy.js
  web/src/components/Instruction.js
  web/src/fixtures/ak-apd.json
  web/src/i18n/locales/en/apd/stateProfile.yaml
  web/src/pages/apd/key-state-personnel/ApdKeyPersonForm.js
  web/src/pages/apd/key-state-personnel/ApdKeyPersonForm.test.js
  web/src/pages/apd/key-state-personnel/ApdKeyPersonReview.js
  web/src/pages/apd/key-state-personnel/ApdKeyPersonReview.test.js
  web/src/pages/apd/key-state-personnel/ApdStateKeyPersonnel.js
  web/src/pages/apd/key-state-personnel/ApdStateKeyPersonnel.test.js
  web/src/pages/apd/key-state-personnel/KeyStatePersonnel.js
  web/src/pages/apd/key-state-personnel/__snapshots__/ApdKeyPersonForm.test.js.snap
  web/src/pages/apd/key-state-personnel/__snapshots__/ApdKeyPersonReview.test.js.snap
  web/src/pages/apd/key-state-personnel/__snapshots__/ApdStateKeyPersonnel.test.js.snap
  web/src/pages/apd/new/ApdNew.js
  web/src/redux/reducers/apd.js
  web/src/redux/reducers/apd.test.js
  web/src/redux/selectors/apd.selectors.js
  yarn.lock
Labels: feature

#4485 Dmirano/4476 remove hit hie tables
  web/src/fixtures/ak-apd-mmis.json
  web/src/fixtures/ak-apd.json
  web/src/fixtures/ak-budget-mmis.json
  web/src/pages/apd/proposed-budget/CombinedActivityCosts.js
  web/src/pages/apd/proposed-budget/ProposedBudget.js
  web/src/pages/apd/proposed-budget/ProposedBudget.test.js
  web/src/pages/apd/proposed-budget/__snapshots__/ProposedBudget.test.js.snap
Labels: feature

#4477 Dmirano/4447 cypress fixtures refactor
  e2e/cypress/fixtures/mmis-basics.json
  e2e/cypress/helpers/apd/activity/check-default-activity.js
  e2e/cypress/integration/02-apd/01-apd-basics.cy.js
  e2e/cypress/integration/05-mmis/01-mmis-basics.cy.js
  e2e/cypress/page-objects/activity-page.js
  e2e/cypress/support/commands.js
Labels: tests
