Repository Enterprise-CMCS/eAPD, pull requests merged in 2023-04, with the labels that each got.

#4642 4613 [Feature] Create Read-only view for Conditions for Enhanced Funding
  .circleci/config.yml
  e2e/cypress/helpers/apd/activity/check-default-activity.js
  e2e/cypress/integration/02-apd/01-apd-basics.cy.js
  e2e/cypress/page-objects/export-page.js
  owasp-test.sh
  web/src/pages/apd/activities/activities-dashboard/ActivityReadOnly.js
  web/src/pages/apd/activities/enhanced-funding/ConditionsForEnhancedFundingReadOnly.js
  web/src/pages/apd/activities/enhanced-funding/ConditionsForEnhancedFundingReadOnly.stories.js
  web/src/pages/apd/activities/enhanced-funding/ConditionsForEnhancedFundingReadOnly.test.js
  yarn.lock
Labels: feature

#4667 4500 Add MDBT Budget Tables to Proposed Budget
  api/migrations/20230329143217_mongoose-add-key-state-personnel-to-ddi-mando.js
  common/utils/budget-default.test.js
  common/utils/budget.js
  common/utils/budget.test.js
  common/utils/constants.js
  common/utils/index.js
  common/utils/test-data/calculateBudget.js
  common/utils/test-data/exampleMMISBudget.js
  e2e/cypress/fixtures/budget-checks-test.json
  e2e/cypress/fixtures/proposed-budget-test.json
  web/src/fixtures/ak-budget-mmis.json
  web/src/i18n/locales/en/proposedBudget.yaml
  web/src/pages/apd/activities/activities-dashboard/__snapshots__/ActivitiesDashboard.test.js.snap
  web/src/pages/apd/proposed-budget/BudgetSummary.js
  web/src/pages/apd/proposed-budget/BudgetSummary.stories.js
  web/src/pages/apd/proposed-budget/BudgetSummary.test.js
  web/src/pages/apd/proposed-budget/CombinedActivityCosts.js
  web/src/pages/apd/proposed-budget/CombinedActivityCosts.test.js
  web/src/pages/apd/proposed-budget/ProposedBudget.js
  web/src/pages/apd/proposed-budget/SummaryBudgetByActivityTotalsHITECH.stories.js
  web/src/pages/apd/proposed-budget/SummaryBudgetByActivityTotalsMMIS.stories.js
  web/src/pages/apd/proposed-budget/__snapshots__/BudgetSummary.test.js.snap
  web/src/pages/apd/proposed-budget/__snapshots__/CombinedActivityCosts.test.js.snap
  web/src/styles/scss/tables.scss
  yarn.lock
Labels: feature

#4670 4575 State Priorities and Scope admin check issue
  web/src/pages/apd/state-priorities-and-scope/StatePrioritiesAndScope.js
  web/src/pages/apd/state-priorities-and-scope/StatePrioritiesAndScope.test.js
  yarn.lock
Labels: bug

#4636 4474 Executive Summary update for MMIS
  e2e/cypress/helpers/mmis/mmis-navigation.js
  web/src/i18n/locales/en/executiveSummary.yaml
  web/src/pages/apd/executive-summary/ExecutiveSummaryBudget.js
  web/src/pages/apd/executive-summary/MmisBudgetSummary.js
  web/src/pages/apd/executive-summary/MmisBudgetSummary.stories.js
  web/src/pages/apd/executive-summary/MmisBudgetSummary.test.js
  web/src/pages/apd/executive-summary/__snapshots__/MmisBudgetSummary.test.js.snap
Labels: feature

#4675 Dmirano/4530 mmis cypress navigation
  .gitignore
  e2e/cypress/helpers/mmis/mmis-navigation.js
  e2e/cypress/integration/05-mmis/01-mmis-basics.cy.js
  e2e/package.json
  web/src/pages/apd/ApdReadOnly.test.js
  web/src/pages/apd/activities/cost-allocation/CostAllocation/OtherFunding.js
  web/src/pages/apd/executive-summary/ActivityExecutiveSummary.js
  web/src/pages/apd/executive-summary/ExecutiveSummary.js
  web/src/pages/apd/key-state-personnel/KeyStatePersonnelReadOnly.js
  web/src/util/apd.js
  yarn.lock
Labels: tests

#4674 4556 Updates to export/read-only proposed budget section
  web/src/pages/apd/proposed-budget/BudgetSummary.js
  web/src/pages/apd/proposed-budget/BudgetSummary.test.js
  web/src/pages/apd/proposed-budget/ProposedBudgetReadOnly.js
  web/src/pages/apd/proposed-budget/__snapshots__/BudgetSummary.test.js.snap
  web/src/pages/apd/security-planning/SecurityPlanningReadOnly.js
Labels: feature

#4679 Dmirano/4531 mmis cypress admin check
  api/util/adminCheck.test.js
  common/schemas/statePrioritiesAndScope.js
  e2e/cypress/helpers/apd/state-priorities-and-scope.js
  e2e/cypress/helpers/mmis/mmis-admin-check.js
  e2e/cypress/integration/05-mmis/01-mmis-basics.cy.js
Labels: tests

#4676 changes needed for setting up dev Okta account
  .circleci/config.yml
  README.md
  api/auth/oktaAuth.js
  api/seeds/shared/set-up-users.js
  api/test-data/test_feature_flags.json
  bin/preview-deploy/aws.sh
  bin/preview-deploy/aws.user-data.sh
  bin/prod-deploy/aws.sh
  docker-compose.endpoint-tests.yml
  docker-compose.yml
  documentation/eAPD_Users.csv
  e2e/cypress-setup.sh
  e2e/cypress/integration/03-admin/02-state-admin-letters.cy.js
  e2e/cypress/integration/03-admin/03-state-admin-portal.cy.js
  e2e/cypress/integration/03-admin/04-admin-check.cy.js
  e2e/cypress/support/commands.js
  e2e/package.json
  packer/mongo-ami.pkr.hcl
  packer/mongo20220708.sh
  packer/preview-ami.pkr.hcl
  packer/preview20230405.sh
  terraform/legacy/preview/modules/databases/variables.tf
  terraform/legacy/preview/preview.tf
  terraform/legacy/preview/variables.tf
  web/src/pages/login/SelectAffiliation.js
  web/src/pages/login/SelectAffiliation.test.js
Labels: refactor

#4688 Add link to updated adminCheck Documentation
  api/util/adminCheck.js
Labels: maintenance

#4685 4672 [Bug] Key State Personnel being added to Executive Summary - Activities Totals
  e2e/cypress/page-objects/executive-summary-page.js
  e2e/cypress/page-objects/export-page.js
  web/src/components/FFYList.js
  web/src/pages/apd/executive-summary/ActivityExecutiveSummary.js
  web/src/pages/apd/executive-summary/ActivityExecutiveSummary.test.js
  web/src/pages/apd/executive-summary/ExecutiveSummary.js
  web/src/pages/apd/executive-summary/ExecutiveSummary.test.js
  web/src/pages/apd/executive-summary/ExecutiveSummaryBudget.js
  web/src/pages/apd/executive-summary/ExecutiveSummaryReadOnly.js
  web/src/pages/apd/executive-summary/__snapshots__/ExecutiveSummaryReadOnly.test.js.snap
  web/src/util/apd.js
Labels: bug

#4684 Dmirano/4532 cypress valid mmis apd
  codecov.yml
  e2e/cypress/fixtures/mmis-with-data.json
  e2e/cypress/helpers/apd/activity/add-MMIS-activity.js
  e2e/cypress/helpers/apd/apd-overview.js
  e2e/cypress/helpers/apd/key-state-personnel.js
  e2e/cypress/helpers/apd/results-of-previous-activities.js
  e2e/cypress/helpers/apd/state-priorities-and-scope.js
  e2e/cypress/helpers/mmis/mmis-security-planning.js
  e2e/cypress/integration/05-mmis/01-mmis-basics.cy.js
  e2e/cypress/integration/05-mmis/03-mmis-apd-with-data.cy.js
  e2e/cypress/page-objects/previous-activities-page.js
  e2e/cypress/support/commands.js
  web/src/pages/apd/previous-activities/MmisApdPreviousActivityTables.js
Labels: tests

#4689 updated npm modules for all green updates
  api/package.json
  common/package.json
  e2e/package.json
  package.json
  web/.storybook/preview.js
  web/package.json
  web/src/components/__snapshots__/UnexpectedError.test.js.snap
  web/src/layout/header/__snapshots__/ApdHeader.test.js.snap
  web/src/layout/header/__snapshots__/Header.test.js.snap
  web/src/pages/apd/activities/oms/OutcomesAndMetrics/__snapshots__/OutcomeAndMetricForm.test.js.snap
  web/src/pages/apd/key-state-personnel/__snapshots__/ApdKeyPersonForm.test.js.snap
  yarn.lock
Labels: maintenance
