Repository Enterprise-CMCS/eAPD, pull requests merged in 2023-03, with the labels that each got.

#4552 Tbolt/4523 Dont allow blank strings in text input fields
  common/schemas/activityOverview.js
  common/schemas/apdNew.js
  common/schemas/apdOverview.js
  common/schemas/assurancesAndCompliance.js
  common/schemas/conditionsForEnhancedFunding.js
  common/schemas/contractorResources.js
  common/schemas/costAllocationNarrative.js
  common/schemas/expenses.js
  common/schemas/index.js
  common/schemas/keyStatePersonnel.js
  common/schemas/milestones.js
  common/schemas/nameAndFundingSource.js
  common/schemas/outcomeMetric.js
  common/schemas/securityPlanning.js
  common/schemas/statePersonnel.js
  common/schemas/statePrioritiesAndScope.js
  web/src/pages/apd/key-state-personnel/ApdStateProfileMedicaidOffice.js
  web/yaml-tests.js
  yarn.lock
Labels: feature

#4573 Fixed issue with adding and removing years breaking Key State Personnel
  documentation/sequence-diagram-auto-saving.mmd
  documentation/sequence-diagram-auto-saving.png
  web/src/redux/reducers/__snapshots__/patch.test.js.snap
  web/src/redux/reducers/apd.js
  web/src/redux/reducers/apd.test.js
  web/src/redux/reducers/patch.test.js
Labels: bug

#4582 updated Activity Overview read-only for MMIS
  api/knexfile.js
  api/migrations-template.js
  common/utils/constants.js
  e2e/cypress/fixtures/default-activity-template.json
  web/src/pages/apd/ApdReadOnly.js
  web/src/pages/apd/activities/activities-dashboard/ActivitiesDashboardReadOnly.js
  web/src/pages/apd/activities/activities-dashboard/ActivityReadOnly.js
  web/src/pages/apd/activities/activities-dashboard/ActivityReadOnly.test.js
  web/src/pages/apd/activities/overview/ActivitySummaryReadOnly.js
  web/src/pages/apd/activities/overview/ActivitySummaryReadOnly.stories.js
  web/src/pages/apd/activities/overview/ActivitySummaryReadOnly.test.js
Labels: feature

#4587 updated key state personnel
  e2e/cypress/helpers/apd/key-state-personnel.js
  web/src/pages/apd/ApdReadOnly.js
  web/src/pages/apd/key-state-personnel/KeyStatePersonnelReadOnly.js
  web/src/pages/apd/key-state-personnel/KeyStatePersonnelReadOnly.stories.js
  web/src/pages/apd/key-state-personnel/KeyStatePersonnelReadOnly.test.js
Labels: feature

#4584 added tooltip to subform save buttons
  e2e/cypress/integration/02-apd/01-apd-basics.cy.js
  web/src/components/FormAndReviewList.js
Labels: feature

#4581 updated the email address of the Export Instructions
  web/src/pages/apd/export/ExportReadOnly.js
  web/src/pages/apd/export/ExportReadOnly.stories.js
  web/src/pages/apd/export/__snapshots__/ExportReadOnly.test.js.snap
Labels: feature

#4601 Tbolt/4559 update apd overview mmis read only
  web/src/components/MedicaidBusinessAreas.js
  web/src/pages/apd/export/ReadOnlyApd.js
  web/src/pages/apd/export/ReadOnlyApd.stories.js
  web/src/pages/apd/export/ReadOnlyApd.test.js
  web/src/pages/apd/export/__snapshots__/ReadOnlyApd.test.js.snap
  web/src/pages/apd/new/ApdNew.js
  web/src/redux/selectors/apd.selectors.js
  web/src/shared/apd-testing-library.js
  web/src/styles/scss/utilities.scss
  yarn.lock
Labels: feature

#4593 kong changes
  api/endpoint-tests/utils.js
  api/routes/apds/files/post.js
  api/routes/apds/submissions/get.endpoint.js
  api/routes/apds/submissions/get.js
  api/routes/apds/submissions/get.test.js
  api/routes/apds/submissions/index.js
  api/routes/apds/submissions/openApi.js
  api/routes/apds/submissions/post.endpoint.js
  api/routes/apds/submissions/post.js
  api/routes/apds/submissions/post.test.js
  web/src/pages/apd/assurances-and-compliance/AssurancesAndComplianceReadOnly.js
Labels: feature

#4614 Alternatives and Risks
  web/src/components/ApdUpdate.js
  web/src/components/MedicaidBusinessAreas.js
  web/src/i18n/locales/en/activities/activities.yaml
  web/src/i18n/locales/en/activities/alternativesAndRisks.yaml
  web/src/i18n/locales/en/activities/comprehensiveOverview.yaml
  web/src/i18n/locales/en/activities/otherFunding.yaml
  web/src/i18n/locales/en/activities/outcomes.yaml
  web/src/i18n/locales/en/activities/overview.yaml
  web/src/pages/apd/activities/activities-dashboard/ActivitiesDashboard.js
  web/src/pages/apd/activities/alternatives-and-risks/AlternativesAndRisks.js
  web/src/pages/apd/activities/alternatives-and-risks/AlternativesAndRisks.stories.js
  web/src/pages/apd/activities/alternatives-and-risks/AlternativesAndRisks.test.js
  web/src/pages/apd/activities/cost-allocation/CostAllocateFFPQuarterly.js
  web/src/pages/apd/activities/ffp/FedStateSelector.js
  web/src/pages/apd/activities/ffp/MatchRateSelector.js
  web/src/pages/apd/activities/overview/HITECHOverview.js
  web/src/pages/apd/activities/overview/MMISOverview.js
  web/src/pages/apd/apd-overview/ApdOverview.js
  web/src/pages/apd/apd-overview/ApdOverviewHITECHFields.js
  web/src/pages/apd/apd-overview/ApdOverviewMMISFields.js
  web/src/pages/apd/proposed-budget/IncentivePayments.js
  web/src/pages/apd/security-planning/SecurityPlanning.js
  web/src/pages/apd/security-planning/SecurityPlanning.test.js
  web/src/pages/apd/state-priorities-and-scope/StatePrioritiesAndScope.js
  web/src/redux/actions/editActivity/alternativesAndRisks.js
  web/src/redux/actions/editActivity/alternativesAndRisks.test.js
  web/src/redux/actions/editActivity/index.js
  web/src/redux/selectors/activities.selectors.js
Labels: feature

#4583 Tbolt/4506 Updates to proposed budget and executive summary
  e2e/cypress/fixtures/budget-checks-test.json
  e2e/cypress/fixtures/proposed-budget-test.json
  e2e/cypress/helpers/apd/activity-schedule-summary.js
  e2e/cypress/integration/02-apd/01-apd-basics.cy.js
  e2e/cypress/page-objects/activity-schedule-page.js
  e2e/cypress/page-objects/budget-page.js
  e2e/cypress/page-objects/export-page.js
  web/package.json
  web/src/components/DollarCell.js
  web/src/i18n/locales/en/proposedBudget.yaml
  web/src/pages/apd/activities/cost-allocation/CostAllocateFFPQuarterly.js
  web/src/pages/apd/activities/cost-allocation/CostAllocateFFPQuarterly.stories.js
  web/src/pages/apd/activities/cost-allocation/CostAllocation/ActivityTotalCostTable.stories.js
  web/src/pages/apd/activities/cost-allocation/CostAllocation/OtherFunding.js
  web/src/pages/apd/activities/cost-allocation/CostAllocationRows.js
  web/src/pages/apd/activities/cost-allocation/CostAllocationRows.test.js
  web/src/pages/apd/activities/cost-allocation/__snapshots__/CostAllocationRows.test.js.snap
  web/src/pages/apd/activities/ffp/CostAllocateFFP.js
  web/src/pages/apd/activities/ffp/FedStateSelector.js
  web/src/pages/apd/activities/ffp/MatchRateSelector.js
  web/src/pages/apd/activities/ffp/__snapshots__/CostAllocateFFP.test.js.snap
  web/src/pages/apd/executive-summary/ExecutiveSummary.js
  web/src/pages/apd/executive-summary/ExecutiveSummaryBudget.stories.js
  web/src/pages/apd/executive-summary/HitechBudgetSummary.js
  web/src/pages/apd/executive-summary/MmisBudgetSummary.js
  web/src/pages/apd/proposed-budget/BudgetSummary.js
  web/src/pages/apd/proposed-budget/BudgetSummary.stories.js
  web/src/pages/apd/proposed-budget/CombinedActivityCosts.js
  web/src/pages/apd/proposed-budget/CombinedActivityCosts.stories.js
  web/src/pages/apd/proposed-budget/IncentivePayments.js
  web/src/pages/apd/proposed-budget/IncentivePayments.stories.js
  web/src/pages/apd/proposed-budget/QuarterlyBudgetSummary.stories.js
  web/src/pages/apd/proposed-budget/SummaryActivityBreakdown.js
  web/src/pages/apd/proposed-budget/SummaryActivityBreakdown.stories.js
  web/src/pages/apd/proposed-budget/SummaryKeyStatePersonnel.js
  web/src/pages/apd/proposed-budget/SummaryKeyStatePersonnel.test.js
  web/src/pages/apd/proposed-budget/__snapshots__/BudgetSummary.test.js.snap
  web/src/pages/apd/proposed-budget/__snapshots__/CombinedActivityCosts.test.js.snap
  web/src/pages/apd/proposed-budget/__snapshots__/SummaryActivityBreakdown.test.js.snap
  web/src/pages/apd/schedule-summary/ScheduleSummary.js
  web/src/pages/apd/schedule-summary/ScheduleSummary.stories.js
  web/src/pages/apd/schedule-summary/ScheduleSummaryReadOnly.js
  web/src/pages/apd/schedule-summary/__snapshots__/ScheduleSummary.test.js.snap
  web/src/styles/scss/tables.scss
  yarn.lock
Labels: content, feature

#4626 Updates the doc link permissions, adds new doc, adds new link to doc
  api/__files/InstructionsAndDelegationForm-StateAdministrators.pdf
  api/api.js
  api/endpoint-tests/utils.js
  api/routes/docs/__snapshots__/get.endpoint.js.snap
  api/routes/docs/get.endpoint.js
  api/routes/docs/get.js
  api/routes/docs/get.test.js
  api/routes/index.js
  api/routes/index.test.js
  api/routes/roles/__snapshots__/get.endpoint.js.snap
  api/test-data/files/InstructionsAndDelegationForm-StateAdministrators.pdf
  web/src/pages/login/Login.js
Labels: feature

#4619 Tbolt/4602 Update help text on cost allocation and other funding page for MMIS
  web/src/i18n/locales/en/activities/costAllocate.yaml
  web/src/i18n/locales/en/activities/otherFunding.yaml
  web/src/pages/apd/activities/cost-allocation/CostAllocation/OtherFunding.js
  web/src/pages/apd/activities/cost-allocation/CostAllocation/OtherFunding.test.js
  yarn.lock
Labels: content

#4616 Dmirano/4571 prev activities mmis read only
  web/src/pages/apd/previous-activities/MmisApdPreviousActivityTables.js
  web/src/pages/apd/previous-activities/PreviousActivities.stories.js
  web/src/pages/apd/previous-activities/__snapshots__/MmisApdPreviousActivityTables.test.js.snap
Labels: feature

#4618 4599 [Feature] Create Read-Only view for Analysis of Alternatives and Risk
  web/src/pages/apd/activities/activities-dashboard/ActivityReadOnly.js
  web/src/pages/apd/activities/alternatives-and-risks/AlternativesAndRisksReadOnly.js
  web/src/pages/apd/activities/alternatives-and-risks/AlternativesAndRisksReadOnly.stories.js
  web/src/pages/apd/activities/alternatives-and-risks/AlternativesAndRisksReadOnly.test.js
Labels: feature

#4643 [maintenance] resolved migration issue
  api/db/apds.js
  api/migrations/20230207224139_mongoose-adding-funding-category.js
  api/migrations/20230327181241_update-budgets.js
  api/models/index.js
Labels: maintenance

#4630 4624 Navigating between activities using the nav menu doesn't update the Activity Name
  e2e/cypress/integration/04-bug-tests/01-state-staff-bugs.cy.js
  web/src/pages/apd/activities/overview/NameForm.js
Labels: bug

#4646 clean up budget migrations
  api/migrations/20230207224139_mongoose-adding-funding-category.js
  api/migrations/20230224154256_mongoose-mmis-budget-match-rate.js
  api/migrations/20230327181241_mongoose-update-budgets.js
  bin/prod-deploy/aws.sh
Labels: maintenance

#4628 4612 [Feature] Create component for Conditions for Enhanced Funding
  common/schemas/conditionsForEnhancedFunding.js
  web/src/components/Icons.js
  web/src/components/StandardsAndConditionsHelpDrawer.js
  web/src/components/StandardsAndConditionsHelpDrawer.stories.js
  web/src/components/StandardsAndConditionsHelpDrawer.test.js
  web/src/i18n/locales/en/activities/conditions.yaml
  web/src/pages/apd/activities/__snapshots__/ActivityRoutes.test.js.snap
  web/src/pages/apd/activities/activityRoutesList.js
  web/src/pages/apd/activities/alternatives-and-risks/AlternativesAndRisks.test.js
  web/src/pages/apd/activities/conditions/ConditionsForEnhancedFunding.js
  web/src/pages/apd/activities/enhanced-funding/ConditionsForEnhancedFunding.js
  web/src/pages/apd/activities/enhanced-funding/ConditionsForEnhancedFunding.stories.js
  web/src/pages/apd/activities/enhanced-funding/ConditionsForEnhancedFunding.test.js
  web/src/redux/actions/editActivity/conditionsForEnhancedFunding.js
  web/src/redux/actions/editActivity/conditionsForEnhancedFunding.test.js
  web/src/redux/actions/editActivity/index.js
  web/src/redux/reducers/nav.items.js
  web/src/redux/selectors/activities.selectors.js
  web/src/styles/scss/forms.scss
  web/src/styles/scss/utilities.scss
Labels: feature
