Repository Enterprise-CMCS/eAPD, pull requests merged in 2023-02, with the labels that each got.

#4498 Tforkner/4376 upgrades
  .circleci/config.yml
  .github/workflows/storybook.yml
  .nvmrc
  README.md
  StatementOfObjectives.md
  api/Dockerfile
  api/package.json
  api/test-server-setup.sh
  bin/preview-deploy/aws.user-data.sh
  bin/prod-deploy/aws.user-data.sh
  codecov.yml
  common/package.json
  common/schemas/apdNew.js
  e2e/package.json
  package.json
  packer/backend20220608.sh
  packer/mongo20220708.sh
  packer/preview20220608.sh
  web/Dockerfile
  web/package.json
  web/src/components/__snapshots__/UnexpectedError.test.js.snap
  web/src/layout/header/__snapshots__/ApdHeader.test.js.snap
  web/src/layout/header/__snapshots__/Header.test.js.snap
  web/src/pages/apd/activities/contractor-costs/ContractorResource/ContractorResourceForm.js
  web/src/pages/apd/activities/oms/OutcomesAndMetrics/OutcomeAndMetricForm.js
  web/src/pages/apd/activities/oms/OutcomesAndMetrics/__snapshots__/OutcomeAndMetricForm.test.js.snap
  web/src/pages/apd/activities/overview/HITECHOverview.js
  web/src/pages/apd/activities/overview/HITECHOverview.test.js
  web/src/pages/apd/activities/schedule-and-milestones/Milestone/MilestoneForm.js
  web/src/pages/apd/activities/state-costs/NonPersonnelCost/NonPersonnelCostForm.js
  web/src/pages/apd/activities/state-costs/NonPersonnelCost/NonPersonnelCostForm.test.js
  web/src/pages/apd/activities/state-costs/StatePerson/StatePersonForm.js
  web/src/pages/apd/export/__snapshots__/ApdExport.test.js.snap
  web/src/pages/apd/key-state-personnel/ApdKeyPersonForm.js
  web/src/pages/apd/key-state-personnel/__snapshots__/ApdKeyPersonForm.test.js.snap
  web/src/pages/apd/new/ApdNew.js
  web/src/pages/apd/new/ApdNew.test.js
  web/src/pages/apd/proposed-budget/IncentivePayments.js
  web/src/pages/apd/proposed-budget/QuarterlyBudgetSummary.js
  web/src/pages/apd/proposed-budget/__snapshots__/QuarterlyBudgetSummary.test.js.snap
  yarn.lock
Labels: dependencies

#4515 fixes to migration issue
  api/migrations/1671458857144-key-state-personnel-mmis.js
  api/migrations/20221222204833_mongoose-hitech-mmis-split.js
  api/migrations/20230126204833_mongoose-key-state-personnel-mmis.js
  common/utils/budget.js
  yarn.lock
Labels: bug

#4484 Nz/4354 priorities scope
  api/util/adminCheck.js
  api/util/adminCheck.test.js
  codecov.yml
  common/schemas/statePrioritiesAndScope.js
  e2e/cypress/fixtures/state-priorities-and-scope.json
  e2e/cypress/helpers/apd/apd-overview.js
  e2e/cypress/helpers/apd/state-priorities-and-scope.js
  e2e/cypress/integration/05-mmis/02-default-mmis-apd.cy.js
  e2e/cypress/integration/05-mmis/03-mmis-apd-with-data.cy.js
  e2e/cypress/support/commands.js
  web/jest.config.js
  web/src/components/TempAlert.js
  web/src/i18n/locales/en/statePrioritiesAndScope.yaml
  web/src/pages/apd/state-priorities-and-scope/StatePrioritiesAndScope.js
  web/src/pages/apd/state-priorities-and-scope/StatePrioritiesAndScope.test.js
  web/src/redux/actions/editApd/statePrioritiesAndScope.js
  web/src/redux/actions/editApd/statePrioritiesAndScope.test.js
  web/src/redux/selectors/apd.selectors.js
Labels: feature

#4499 Dmirano/3493 mmis activities dashboard
  web/src/i18n/locales/en/activities/activities.yaml
  web/src/i18n/locales/en/securityPlanning.yaml
  web/src/pages/apd/activities/activities-dashboard/ActivitiesDashboard.js
  web/src/pages/apd/activities/activities-dashboard/ActivitiesDashboard.test.js
  web/src/pages/apd/activities/activities-dashboard/Activity.js
  web/src/pages/apd/activities/activities-dashboard/Activity.test.js
  web/src/pages/apd/activities/activities-dashboard/__snapshots__/Activity.test.js.snap
  web/src/pages/apd/security-planning/SecurityPlanning.js
  web/src/pages/apd/security-planning/SecurityPlanning.test.js
Labels: feature

#4518 Dmirano/4363 remove hit hie tables prev activities
  e2e/cypress/fixtures/mmis-basics.json
  e2e/cypress/integration/05-mmis/01-mmis-basics.cy.js
  web/src/pages/apd/previous-activities/ApdPreviousActivityTableTotal.js
  web/src/pages/apd/previous-activities/ApdPreviousActivityTableTotal.test.js
  web/src/pages/apd/previous-activities/PreviousActivities.js
  web/src/pages/apd/previous-activities/PreviousActivities.test.js
  web/src/pages/apd/previous-activities/PreviousActivitiesReadOnly.js
  web/src/pages/apd/previous-activities/__snapshots__/PreviousActivities.test.js.snap
  web/src/redux/selectors/apd.selectors.js
Labels: feature

#4522 NZ/4501 - can add/remove years
  api/seeds/development/03-mmis.js
  api/seeds/development/04-mmisNoActivities.js
  e2e/cypress/helpers/apd/apd-overview.js
  e2e/cypress/integration/05-mmis/03-mmis-apd-with-data.cy.js
  web/src/pages/apd/new/ApdNew.test.js
  web/src/redux/reducers/__snapshots__/patch.test.js.snap
  web/src/redux/reducers/apd.js
  web/src/redux/reducers/apd.test.js
Labels: feature

#4526 Nz/4304 Update Budget and FFP for MMIS
  e2e/cypress/fixtures/default-mmis-activity-template.json
  e2e/cypress/helpers/mmis/activity/default-activity.js
  e2e/cypress/integration/05-mmis/02-default-mmis-apd.cy.js
  web/src/pages/apd/activities/ffp/CostAllocateFFP.js
Labels: feature

#4535 dmirano/4513-activities-dashboard-help-text
  web/src/i18n/locales/en/activities/activities.yaml
  web/src/pages/apd/activities/activities-dashboard/ActivitiesDashboard.js
  web/src/pages/apd/activities/activities-dashboard/ActivitiesDashboard.test.js
Labels: feature

#4536 dmirano/4509-outcomes-and-metrics-help-text
  web/src/components/__snapshots__/Section.test.js.snap
  web/src/i18n/locales/en/activities/outcomes.yaml
  web/src/pages/apd/activities/oms/Outcomes.js
  web/src/pages/apd/activities/oms/Outcomes.test.js
  web/src/pages/apd/activities/oms/__snapshots__/Outcomes.test.js.snap
Labels: feature

#4546 Dmirano/4510 state staff and expenses help text
  web/src/i18n/locales/en/activities/expenses.yaml
  web/src/i18n/locales/en/activities/statePersonnel.yaml
  web/src/pages/apd/activities/state-costs/NonPersonnelCosts.js
  web/src/pages/apd/activities/state-costs/NonPersonnelCosts.test.js
  web/src/pages/apd/activities/state-costs/StatePersonnel.js
  web/src/pages/apd/activities/state-costs/StatePersonnel.test.js
  web/src/pages/apd/activities/state-costs/__snapshots__/NonPersonnelCosts.test.js.snap
  web/src/pages/apd/activities/state-costs/__snapshots__/StatePersonnel.test.js.snap
Labels: feature

#4544 Tbolt/4511 Private Contractor Example Help Text Update
  web/src/i18n/locales/en/activities/contractorResources.yaml
  web/src/pages/apd/activities/contractor-costs/ContractorResources.js
  web/src/pages/apd/activities/contractor-costs/ContractorResources.test.js
  web/src/pages/apd/activities/contractor-costs/__snapshots__/ContractorResources.test.js.snap
Labels: content

#4543 Tbolt/4491 medicaid business areas bug
  web/src/pages/apd/activities/activities-dashboard/ActivitiesDashboard.js
  web/src/pages/apd/activities/activities-dashboard/Activity.js
  web/src/pages/apd/new/ApdNew.js
  web/src/pages/apd/new/ApdNew.test.js
  web/src/pages/apd/new/__snapshots__/ApdNew.test.js.snap
  web/src/pages/apd/previous-activities/ApdPreviousActivityTableTotal.js
  web/src/pages/apd/previous-activities/PreviousActivities.js
  web/src/pages/apd/previous-activities/PreviousActivitiesReadOnly.js
  yarn.lock
Labels: bug

#4548 Tbolt/4512 Updates to help text in cost allocation for MMIS apds
  web/src/i18n/locales/en/activities/costAllocate.yaml
  web/src/pages/apd/activities/cost-allocation/CostAllocation/CostAllocate.js
  web/src/pages/apd/activities/cost-allocation/CostAllocation/CostAllocate.test.js
Labels: content

#4528 Ad/4211 MMIS APD overview
  api/seeds/development/01-hitech.js
  api/seeds/development/02-hitechNoActivities.js
  api/util/adminCheck.js
  api/util/adminCheck.test.js
  common/schemas/apdNew.js
  common/schemas/apdOverview.js
  common/schemas/combined.js
  common/schemas/index.js
  common/utils/constants.js
  e2e/cypress/helpers/apd/apd-name.js
  e2e/cypress/helpers/apd/apd-overview.js
  e2e/cypress/integration/02-apd/01-apd-basics.cy.js
  e2e/cypress/integration/02-apd/02-default-apd.cy.js
  e2e/cypress/integration/02-apd/03-apd-with-data.cy.js
  e2e/cypress/integration/02-apd/04-apd-budget-checks.cy.js
  e2e/cypress/integration/03-admin/04-admin-check.cy.js
  e2e/cypress/integration/04-bug-tests/01-state-staff-bugs.cy.js
  e2e/cypress/integration/05-mmis/01-mmis-basics.cy.js
  e2e/cypress/integration/05-mmis/02-default-mmis-apd.cy.js
  e2e/cypress/integration/05-mmis/03-mmis-apd-with-data.cy.js
  web/src/components/ApdUpdate.js
  web/src/components/ApdUpdate.test.js
  web/src/components/Instruction.js
  web/src/components/Instruction.test.js
  web/src/components/__snapshots__/Section.test.js.snap
  web/src/i18n/locales/en/apd/apd.yaml
  web/src/layout/header/ApdHeader.js
  web/src/layout/header/__snapshots__/ApdHeader.test.js.snap
  web/src/pages/apd/activities/state-costs/__snapshots__/NonPersonnelCosts.test.js.snap
  web/src/pages/apd/activities/state-costs/__snapshots__/StatePersonnel.test.js.snap
  web/src/pages/apd/apd-overview/ApdOverview.js
  web/src/pages/apd/apd-overview/ApdOverview.test.js
  web/src/pages/apd/apd-overview/ApdOverviewHITECHFields.js
  web/src/pages/apd/apd-overview/ApdOverviewHITECHFields.test.js
  web/src/pages/apd/apd-overview/ApdOverviewMMISFields.js
  web/src/pages/apd/apd-overview/ApdOverviewMMISFields.test.js
  web/src/pages/apd/proposed-budget/__snapshots__/CombinedActivityCosts.test.js.snap
  web/src/redux/actions/editApd/overview.js
  web/src/redux/actions/editApd/overview.test.js
  web/src/styles/scss/utilities.scss
Labels: feature

#4517 Tbolt/4416 mmis proposed budget
  api/models/budget.js
  api/routes/openAPI/__snapshots__/get.endpoint.js.snap
  api/routes/openAPI/index.js
  common/schemas/keyStatePersonnel.js
  common/utils/budget.js
  common/utils/budget.test.js
  e2e/cypress/fixtures/HIE-activity-template.json
  e2e/cypress/fixtures/HIT-activity-template.json
  e2e/cypress/fixtures/MMIS-activity-template.json
  e2e/cypress/fixtures/budget-checks-test.json
  e2e/cypress/fixtures/default-activity-template.json
  e2e/cypress/fixtures/default-mmis-activity-template.json
  e2e/cypress/fixtures/proposed-budget-test.json
  e2e/cypress/helpers/apd/proposed-budget-calculations.js
  web/src/fixtures/ak-apd-mmis.json
  web/src/fixtures/ak-budget-mmis.json
  web/src/fixtures/mo-hitech-apd.js
  web/src/i18n/locales/en/proposedBudget.yaml
  web/src/pages/apd/activities/contractor-costs/ContractorResources.stories.js
  web/src/pages/apd/activities/cost-allocation/CostAllocationRows.js
  web/src/pages/apd/activities/cost-allocation/CostAllocationRows.test.js
  web/src/pages/apd/activities/cost-allocation/__snapshots__/CostAllocationRows.test.js.snap
  web/src/pages/apd/activities/ffp/__snapshots__/CostAllocateFFP.test.js.snap
  web/src/pages/apd/proposed-budget/BudgetSummary.js
  web/src/pages/apd/proposed-budget/BudgetSummary.test.js
  web/src/pages/apd/proposed-budget/CombinedActivityCosts.js
  web/src/pages/apd/proposed-budget/CombinedActivityCosts.test.js
  web/src/pages/apd/proposed-budget/ProposedBudget.js
  web/src/pages/apd/proposed-budget/ProposedBudget.test.js
  web/src/pages/apd/proposed-budget/ProposedBudgetReadOnly.js
  web/src/pages/apd/proposed-budget/SummaryKeyStatePersonnel.js
  web/src/pages/apd/proposed-budget/SummaryKeyStatePersonnel.test.js
  web/src/pages/apd/proposed-budget/__snapshots__/BudgetSummary.test.js.snap
  web/src/pages/apd/proposed-budget/__snapshots__/CombinedActivityCosts.test.js.snap
  web/src/redux/selectors/activities.selectors.js
  web/src/redux/selectors/activities.selectors.test.js
  yarn.lock
Labels: feature
